### PR TITLE
presentations.tid - further tweaks

### PR DESCRIPTION
**Pull request by twMat**

### CODE REVIEW

**Comment by twMat** [comment]
No good? Feel free to close.

**Comment by danielo515** [comment]
Sorry @twMat , forget about this. I wanted to ask you about the reason of this change:

```
style="display: block; margin: 0 auto;"
```

Why do you think it is needed to hardcode those styles? Which problem are you trying to solve?

Many thanks

**Comment by twMat** [comment]
IMO the following simply looks like the image is off. 
The text has a max-width and is centered with equal margins left and right, so it makes sense for the big image to also behave like this.

image

By the way, to my surprise I tested to zoom out (even just one step to 90%) and the top image shows instead on the side. I must assume this is intentional, but I had not noticed before. However, there is a need for some margins around (all) the images:

image

...but these are purely aesthetic matters and simply a matter of opinion. If you disagree then just ignore, no prob.

**Comment by danielo515** [comment]
Hello @twMat ,

I'm very happy to discuss with you the aesthetic of the website, it is not necessary to say that I can ignore the pull request, I indeed want to merge all your proposals.

What you are describing is called responsive design. If the screen is wide enough to display both the image and the text, they will be shown inline, if not, they will have full width. I'm curious about your screen resolution, because on all my screens it display the wider version, it's only on mobile where they have full width, and the lack of alignment you describe is not noticeable. 

I agree that images needs some margins, but I prefer to add padding instead of margin when possible.
However, I would prefer to merge style modifications on a style dedicated pull request. If you are willing to remove the styles and leave your other modifications I will be very happy to merge this pull request.

**Comment by danielo515** [comment]
If you want to play with styles, here is the sheet:

https://github.com/NoteSelf/NoteSelf.github.io/blob/develop/wiki/tiddlers/Site/site_styles.css.tid

**Comment by twMat** [comment]
Hehe - yes I know about responsive design. I was just surprised to see a breakpoint kick in at only one zoom level difference. Usually there is a bigger discrepancy, such as going from a laptop size screen to a pad or phone. But, as you're also thinking, we probably have different screen resolutions - mine is 1366x768

Margin vs padding - whatever makes you happy ;-)

**Comment by danielo515** [comment]
If you don't mind, I'll remove the inlined styles and accept the pull request. 
Then you can make another pull request for better responsiveness. Are you ok with it?

**Comment by twMat** [comment]
Take the parts you feel are useful.

If I get the urge to put together another PR with responsiveness matters, I'll do so.

**Pull request merged**
